apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cilium-eks
  region: eu-west-2
  version: "1.29"

managedNodeGroups:
- name: ng-1
  desiredCapacity: 2
  privateNetworking: true
  # taint nodes so that application pods are
  # not scheduled/executed until Cilium is deployed.
  # Alternatively, see the note below.
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoExecute"
